# Generated by Django 3.2.3 on 2023-05-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mech',
            name='image',
            field=models.CharField(default='placeholder', max_length=50),
        ),
    ]
